20 loginページsignupページ修正
FltSv/GalleryFound pull request #25
Opened 2023-11-24 11:54 UTC by kurokoutsuki

細かいやつ修正したよ

影色変更

一応PW確認の欄を揃えたけど反映されてなかったら教えてちょ

2023-11-24 23:17 UTC, FltSv requested changes

2023-11-24 23:17 UTC, FltSv commented on Hosting/public/login/index.html
> +                style="width: 180px; height: 30px;"
基本的にHTMLにはstyleを記述せず、CSSに記述して共通化することを検討してみてください。

2023-11-24 23:17 UTC, FltSv commented on Hosting/public/login/styles.css
> +#input-pwd-confirm[type="password"]{
この書き方だと、今後フォームが増えた場合に更にフォーム毎に指定子を追加していくことになるため、非効率です。
例えば下記のようなHTMLがあるとした場合、
```
<input type="text" id="input-id" placeholder="メールアドレス">
<input type="password" id="input-pwd" placeholder="パスワード">
<input type="password" id="input-pwd-confirm" placeholder="パスワード（確認）">
```
それぞれに `class="input-form"` とクラスを適用させてみます（ここで作るクラス名は自分で考えて作る）
```
<input type="text" id="input-id" class="input-form" placeholder="メールアドレス">
<input type="password" id="input-pwd" class="input-form" placeholder="パスワード">
<input type="password" id="input-pwd-confirm" class="input-form" placeholder="パスワード（確認）">
```
HTMLにクラスを付けることで、CSSは以下のように記述すれば、わざわざIdを複数書かずともスタイルの適用が可能になります。
```
.input-form {
  width: 180px;
  height: 20px;
（以下略）
}
```
このように、なるべく共通化することで修正が少なくなるようなコードを検討してみてください。

2023-11-25 01:08 UTC, kurokoutsuki commented on Hosting/public/login/index.html
> +  <!-- ß
んん！？これは何もいじってなかったのですが、間違えて入力しちゃったのかな・・・

2023-12-11 00:13 UTC, FltSv commented on Hosting/public/login/index.html
> +  <!-- ß
いくつかの指摘がResolveされていますが、Resolveは指摘をした人が行うので、指摘をされた人はResolveを行わないよう気をつけてください。
WikiのGit運用フローにも記載がありますので、もう一度目を通しておいて頂きたいです。
![image](https://github.com/FltSv/GalleryFound/assets/23271500/ca2c5858-8030-4c37-83ad-00cfff158b03)

2023-12-20 12:42 UTC, FltSv reviewed
過去の指摘は修正されたことを確認しました。ありがとうございます！
もう1点だけすみません、元々のIssueの文言が分かりにくかったかもしれませんが、signupページ（login/resister.html）の入力フォームも同様にクラスを追記して、loginページと同じスタイルを適用してほしいです。
（1枚目：loginページ、2枚目：signupページ）


![image](https://github.com/FltSv/GalleryFound/assets/23271500/c9d5dba8-3e1f-4394-a48a-79814b7355f1)
![image](https://github.com/FltSv/GalleryFound/assets/23271500/cd1a5f1d-094d-4a9f-85ca-4909ab5bee6d)

2023-12-20 22:57 UTC, FltSv approved these changes

2023-12-21 10:28 UTC, merged